### ISSUE TITLE
Errors with the package

### ISSUE THREAD

**Issue by k0nkupa** [selaias/avatar-manager#4]
![untitled](https://cloud.githubusercontent.com/assets/16287914/11778939/6995c702-a28a-11e5-8cfa-2e6b059d1c77.png)
here is the image, i dont know why it's happening

**Comment by selaias** [comment]
are you using the AvatarManager.setAvailableServices method? If yes it takes an array of services as parameter and a boolean if you want to join those services with the default ones (optional), default is true.

**Comment by k0nkupa** [comment]
i haven't written anything, when i add the package it just appear these crashes

**Comment by selaias** [comment]
I don't get it. is the `ecmascript` included in your package list? what version of Meteor you are using?

**Comment by k0nkupa** [comment]
ecmascript is included in my package list, i'm using ver 6.8.7, the only thing that not included in my package list are insecure and autopublish

**Comment by selaias** [comment]
could you post a repo so I can reproduce the error?

**Comment by k0nkupa** [comment]
sr for my silly question, what is a repo ?

**Comment by selaias** [comment]
no worries, we all been through that. I mean if you could create a repository on github or meteorpad so I can take a look.

**Comment by k0nkupa** [comment]
how to create a repository? or i just zip all my project into .rar ?

**Comment by selaias** [comment]
https://help.github.com/articles/create-a-repo/

make sure you dont commit any sensitive information like logins, passwords, connection settings etc.

**Comment by k0nkupa** [comment]
https://github.com/k0nkupa/chatapp.git
i just copy my js file in here

**Comment by selaias** [comment]
this does not help much, can you post at least the packages file which lies under .meteor folder?
thanks

**Comment by k0nkupa** [comment]
i just upload my packages file tks

**Comment by selaias** [comment]
can you also put the versions file under the .meteor folder.

then replace with this and let me know

accounts-base@1.2.2
accounts-password@1.1.4
accounts-ui@1.1.6
accounts-ui-unstyled@1.1.8
autoupdate@1.2.4
babel-compiler@5.8.24_1
babel-runtime@0.1.4
base64@1.0.4
binary-heap@1.0.4
blaze@2.1.3
blaze-html-templates@1.0.1
blaze-tools@1.0.4
boilerplate-generator@1.0.4
caching-compiler@1.0.0
caching-html-compiler@1.0.2
callback-hook@1.0.4
check@1.1.0
ddp@1.2.2
ddp-client@1.2.1
ddp-common@1.2.2
ddp-rate-limiter@1.0.0
ddp-server@1.2.2
deps@1.0.9
diff-sequence@1.0.1
ecmascript@0.1.6
ecmascript-runtime@0.2.6
ejson@1.0.7
email@1.0.8
es5-shim@4.1.14
fastclick@1.0.7
geojson-utils@1.0.4
hot-code-push@1.0.0
html-tools@1.0.5
htmljs@1.0.5
http@1.1.1
id-map@1.0.4
idorecall:email-normalize@1.0.0
jparker:crypto-core@0.1.0
jparker:crypto-md5@0.1.1
jparker:gravatar@0.4.1
jquery@1.11.4
launch-screen@1.0.4
less@2.5.1
livedata@1.0.15
localstorage@1.0.5
logging@1.0.8
meteor@1.1.10
meteor-base@1.0.1
meteorhacks:inject-initial@1.0.3
minifiers@1.1.7
minimongo@1.0.10
mobile-experience@1.0.1
mobile-status-bar@1.0.6
momentjs:moment@2.10.6
mongo@1.1.3
mongo-id@1.0.1
npm-bcrypt@0.7.8_2
npm-mongo@1.4.39_1
observe-sequence@1.0.7
ordered-dict@1.0.4
promise@0.5.1
random@1.0.5
rate-limit@1.0.0
reactive-dict@1.1.3
reactive-var@1.0.6
reload@1.1.4
retry@1.0.4
routepolicy@1.0.6
selaias:avatar-manager@0.3.0
selaias:avatar-upload@1.3.0
service-configuration@1.0.5
session@1.1.1
sha@1.0.4
spacebars@1.0.7
spacebars-compiler@1.0.7
srp@1.0.4
standard-minifiers@1.0.2
templating@1.1.5
templating-tools@1.0.0
tracker@1.0.9
twbs:bootstrap@3.3.6
ui@1.0.8
underscore@1.0.4
url@1.0.5
utilities:avatar@0.9.2
webapp@1.2.3
webapp-hashing@1.0.5

**Comment by k0nkupa** [comment]
selaias:avatar-manager@0.3.0
selaias:avatar-upload@1.3.0
service-configuration@1.0.5
 mine is 
selaias:avatar-manager@0.3.1
selaias:avatar-upload@1.3.0
service-configuration@1.0.5
and when i replace 0.3.0 it works lol

**Comment by selaias** [comment]
published new version that fixes some dependencies issues. It should be ok now.
Thanks

**Comment by selaias** [comment]
ef67469a5ead4686ce97a1d1159bfb74030c7af6
bd7acf33c0ca626855364d17f76e551a0b52f716
