### ISSUE TITLE
Add a call back for onCreateUser

### ISSUE THREAD

**Issue by heyiamben** [selaias/avatar-manager#5]
Your onCreateUser callback is likely to conflict with other onCreateUser callbacks inside the same app.  
I think it would be better if you had the app developers add the onCreateUser logic themselves.  You can just provide the necessary function calls to make it all work.

**Comment by selaias** [comment]
I guess you are right. I thought you can call this more than once but apparently you should not. 
I'm gonna do some tests over the next days.

**Comment by solace** [comment]
It definitely conflicts. :)

**Comment by selaias** [comment]
sorry about the delay, 
I removed the onCreateUser callback and added a method to call when needed.

89154e7d73ee520ee6b1b91846692af8344e2f4b
