### ISSUE TITLE
Exception in onLogin callback: Error: Match error: Expected plain object

### ISSUE THREAD

**Issue by solace** [selaias/avatar-manager#8]
Hi,

I may be mistaken, but using the suggested `onLogin` fragment, the error

```
Exception in onLogin callback: Error: Match error: Expected plain object
```

Is returned as a result of `check(user, Object);` in the `_setUserAvatar` call because `Meteor.user()` returns a Document and not a plain object.

**Comment by selaias** [comment]
Are you using Safari?
Can you try to add ejson package and see if it solves this? If not I would suggest to replace the code with 

``` js
let user = Meteor.users.findOne({_id: Meteor.userId()});
AvatarManager.setUserAvatar(user);
```

**Comment by solace** [comment]
Chrome. And I've added the ejson package and it still returns that error.

I've added alternative code in my `onCreateUser` callback which sets the image there, similar to your original callback, but I thought I should mention the problem for those installing it as described in the README.

**Comment by selaias** [comment]
can you try the demo site ? I tested it on Chrome and it works.

http://avatarmanager.meteor.com/

**Comment by solace** [comment]
Hi,

If you're sure, then I believe you. :) Given you only just released the update and I've changed my implementation, we'll close it off unless someone else has this problem.

Thanks for looking into it.
